name: setup-mkosi
description: Install mkosi

# https://github.com/actions/runner/issues/2473
inputs:
  action_ref:
    default: ${{ github.action_ref }}
  action_repository:
    default: ${{ github.action_repository }}
runs:
  using: composite
  steps:
    - name: Permit unprivileged access to kvm, vhost-vsock and vhost-net devices
      shell: bash
      run: |
        sudo mkdir -p /etc/tmpfiles.d
        sudo cp /usr/lib/tmpfiles.d/static-nodes-permissions.conf /etc/tmpfiles.d/
        sudo sed -i '/kvm/s/0660/0666/g'   /etc/tmpfiles.d/static-nodes-permissions.conf
        sudo sed -i '/vhost/s/0660/0666/g' /etc/tmpfiles.d/static-nodes-permissions.conf
        sudo tee /etc/udev/rules.d/99-kvm4all.rules <<- EOF
        KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"
        KERNEL=="vhost-vsock", GROUP="kvm", MODE="0666", OPTIONS+="static_node=vhost-vsock"
        KERNEL=="vhost-net", GROUP="kvm", MODE="0666", OPTIONS+="static_node=vhost-net"
        EOF
        sudo udevadm control --reload-rules
        # kvm/vhost might not be available (e.g.: s390x, ppc64le)
        sudo modprobe kvm || true
        sudo modprobe vhost_vsock || true
        sudo modprobe vhost_net || true
        [[ -e /dev/kvm ]] && sudo udevadm trigger --name-match=kvm
        [[ -e /dev/vhost-vsock ]] && sudo udevadm trigger --name-match=vhost-vsock
        [[ -e /dev/vhost-net ]] && sudo udevadm trigger --name-match=vhost-net
        [[ -e /dev/kvm ]] && sudo chmod 666 /dev/kvm
        [[ -e /dev/vhost-vsock ]] && sudo chmod 666 /dev/vhost-vsock
        [[ -e /dev/vhost-net ]] && sudo chmod 666 /dev/vhost-net
        lsmod
        [[ -e /dev/kvm ]] && ls -l /dev/kvm
        [[ -e /dev/vhost-vsock ]] && ls -l /dev/vhost-vsock
        [[ -e /dev/vhost-net ]] && ls -l /dev/vhost-net
        id

    - name: Check clock source
      shell: bash
      run: cat /sys/devices/system/clocksource/clocksource0/current_clocksource

    - name: Show environment
      shell: bash
      run: env

    - name: Show CPU
      shell: bash
      run: lscpu

    - name: Show memory
      shell: bash
      run: lsmem

    - name: Enable unprivileged user namespaces
      shell: bash
      run: |
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_userns=0

    - name: Create missing mountpoints
      shell: bash
      run: |
        sudo mkdir -p /var/lib/ca-certificates

    # Both the unix-chkpwd and swtpm profiles are broken (https://gitlab.com/apparmor/apparmor/-/issues/402) so let's
    # just disable and remove apparmor completely. It's not relevant in this context anyway.
    # TODO: Remove if https://github.com/actions/runner-images/issues/10015 is ever fixed.
    - name: Disable and mask apparmor service
      shell: bash
      run: |
        # This command fails with a non-zero error code even though it unloads the apparmor profiles.
        # https://gitlab.com/apparmor/apparmor/-/issues/403
        sudo aa-teardown || true
        sudo apt-get remove apparmor

    - name: Ensure git history is available
      shell: bash
      run: |
        if [[ ! -d "${{ github.action_path }}/.git" ]]; then
            rm -rf "${{ github.action_path }}"
            git clone "https://github.com/${{ inputs.action_repository }}" "${{ github.action_path }}"
            git -C "${{ github.action_path }}" checkout "${{ inputs.action_ref }}"
        fi

    - name: Install
      shell: bash
      run: sudo ln -svf ${{ github.action_path }}/bin/mkosi /usr/bin/mkosi

    - name: Dependencies
      shell: bash
      run: |
        sudo apt-get install --assume-yes --no-install-recommends \
          debian-archive-keyring \
          dnf \
          makepkg \
          pacman-package-manager \
          zypper
