name: freedesktop-sdk-extra
min-version: 2.5

# Subdirectory where elements are stored
element-path: elements

aliases:
  gitlab: https://gitlab.com/

plugins:
  - origin: pip
    package-name: buildstream-plugins >= 2.4.0
    sources:
    - git
