# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Content]
Packages=
        edk2-riscv64
        qemu-system-aarch64-core
        qemu-system-ppc-core
        qemu-system-riscv-core
        qemu-system-s390x-core
