# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
# BuildStream is a generic distribution so we don't know which package to install.
Distribution=!buildstream

[Content]
Packages=
        systemd                   # sine qua non
        udev
        bash                      # for emergency logins
        less                      # this makes 'systemctl' much nicer to use ;)
        gzip                      # For compressed keymap unpacking by loadkeys
