# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Content]
Packages=
        cryptsetup-libs
        device-mapper
        kbd
        libseccomp
        util-linux
        util-linux-login

        # systemd-repart dependency
        libfdisk
