# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Content]
Packages=
    bash
    systemd-boot
    systemd-networkd # required for systemd-network-generator
    systemd-resolved
    kmod # mkosi expects "full" depmod
    linux-virt
    agetty # required for *getty@ services
    util-linux
    openssh-server
    openssh-server-pam-systemd

Bootable=yes
ShimBootloader=none
