# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Distribution]
Snapshot=2025/08/22

[Content]
Packages=
        grub
        openssh
        python
        qemu-user-static
        shim
