# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=nura

[Content]
Packages=
        grub
        grub-efi
        openssh-server
        openssh-server-pam-systemd

# Nura / Alpine Linux does not ship an unsigned shim
ShimBootloader=none
