# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Content]
Packages=
        apt
        btrfs-progs
        erofs-utils
        # NOTE: grub disabled because package trigger fails
        # grub
        libseccomp
        pacman
        p11-kit
        sbsigntool
        squashfs-tools
        ukify
        xz
