# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Content]
Packages=
        abuild
        apk-tools
        btrfs-progs
        cryptsetup
        distribution-gpg-keys
        erofs-utils
        grub
        grub-efi
        libfido2
        libseccomp
        p11-kit
        sbsigntool
        sfdisk
        squashfs-tools
        ukify
        xz

        # These replace the busybox applets, which don't support the full set of
        # features that mkosi needs
        losetup
        mount
        umount
