# SPDX-License-Identifier: LGPL-2.1-or-later

[Distribution]
Distribution=custom

[Output]
Output=initrd.addon
Format=addon
ManifestFormat=
SplitArtifacts=

[Content]
Bootable=no
MakeInitrd=yes
CleanPackageMetadata=yes

RemoveFiles=
        # Including kernel images in the initrd is generally not useful.
        # This also stops mkosi from extracting the kernel image out of the image as a separate output.
        /usr/lib/modules/*/vmlinuz*
        /usr/lib/modules/*/vmlinux*
        /usr/lib/modules/*/System.map
