# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|amazonlinux

[Content]
Packages=
        openssh-clients
        openssh-server
        python3
        rpm-build
        systemd-resolved
        amazon-cloudwatch-agent
        amazon-ec2-net-utils
        amazon-ecr-credential-helper
        amazon-efs-utils
        amazon-linux-logos
        amazon-linux-sb-keys
        amazon-rpm-config
        amazon-ssm-agent
