# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Repositories=epel
# EPEL 8 (used by Alibaba Cloud Linux 3) does not ship btrfs-progs.
Distribution=!alinux

[Content]
Packages=
        btrfs-progs
