# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|alma
Distribution=|alinux
Distribution=|rocky
Distribution=|centos
Distribution=|fedora
Distribution=|azure

[Content]
Packages=
        iproute
        iputils
        kernel
        polkit
        tpm2-tss
        util-linux
