# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=nura

[Content]
Packages=
        apt
        archlinux-keyring
        pacman
        debian-archive-keyring
        ubuntu-archive-keyring
