#!/bin/bash -x

rm -f ${BUILDROOT}/var/cache/ldconfig/aux-cache
for f in dconf-db dconf-locks fingerprint-auth nsswitch.conf password-auth postlogin smartcard-auth system-auth; do
	sed -i -e 's/Generated by authselect.*//' "${BUILDROOT}/etc/authselect/$f"
done
