# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Distribution]
Release=rawhide

[Content]
# kernel-uki-virt ships a pre-built UKI for virtual machines, needed to test
# Bootloader=uki-prebuilt.
Packages=
        kernel-uki-virt
