#!/bin/sh
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Set up a local mkosi configuration for an integration test scenario and build the tools tree and
# image, so the integration tests can be run afterwards. Run from the repository root:
#
#     tools/integration-test-setup.sh <distribution> <tools-tree-distribution>

set -eu

group() {
    [ -z "${GITHUB_ACTIONS:-}" ] || echo "::group::$1"
}

endgroup() {
    [ -z "${GITHUB_ACTIONS:-}" ] || echo '::endgroup'
}

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <distribution> <tools-tree-distribution>" >&2
    exit 1
fi

distribution="$1"
tools="$2"

group "create_config"

# safety check: don't clobber local config
CI_MARKER='# CI config generated by tools/integration-test-setup.sh'
if [ -e mkosi.local.conf ] && ! grep -qF "$CI_MARKER" mkosi.local.conf; then
    echo "There is an existing mkosi.local.conf, aborting" >&2
    exit 1
fi

cat >mkosi.local.conf <<EOF
${CI_MARKER}
[Distribution]
Distribution=${distribution}

[Output]
ManifestFormat=json

[Content]
KernelCommandLine=systemd.default_device_timeout_sec=180

[Build]
ToolsTreeDistribution=${tools}
Environment=SYSTEMD_REPART_MKFS_OPTIONS_EROFS="--quiet"

[Runtime]
KVM=yes
EOF

# TODO: Remove once all distros have recent enough systemd that knows systemd.default_device_timeout_sec.
mkdir -p mkosi-initrd/mkosi.extra/usr/lib/systemd/system.conf.d
cat >mkosi-initrd/mkosi.extra/usr/lib/systemd/system.conf.d/device-timeout.conf <<EOF
[Manager]
DefaultDeviceTimeoutSec=180
EOF

cat >mkosi.configure <<EOF
#!/bin/bash
echo "Hello from inside mkosi.configure!" >&2
cat
EOF
chmod +x mkosi.configure

# prepare and postinst are already used in CI.
for script in sync build finalize postoutput clean; do
    cat >"mkosi.${script}" <<EOF
#!/bin/bash
echo "Hello from inside mkosi.${script}" >&2
EOF
    chmod +x "mkosi.${script}"
done

endgroup

# avoid pager

group "summary"
bin/mkosi summary </dev/null
endgroup

# Builds

if [ ! -e mkosi.key ]; then
    group "genkey"
    bin/mkosi genkey
    endgroup
fi

group "build_box"
bin/mkosi -f box -- true
endgroup

group "build_image"
bin/mkosi -f
endgroup
