# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
# BuildStream is a generic distribution so we don't know which package to install.
Distribution=!buildstream

[Content]
Packages=
        autoconf
        automake
        binutils
        bison
        bzip2
        cmake
        flex
        gcc
        gettext
        groff
        libtool
        m4
        make
        meson
        patch
        pkgconf
