name: CI CentOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        output_type: [directory, tar, gpt_ext4, gpt_xfs, gpt_btrfs, gpt_squashfs, plain_squashfs]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Update package cache
      run: sudo apt-get --assume-yes update
    - name: Install dependencies
      run: sudo apt-get --assume-yes install systemd-container squashfs-tools e2fsprogs xfsprogs yum
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Build CentOS/${{ matrix.output_type }}
      run: sudo env PATH=$PATH python3 ./mkosi --debug run -d centos -r 8 -t ${{ matrix.output_type }} -p tzdata -b false --default /dev/null
